### ISSUE TITLE
Plugin detects more dependencies than mvn dependency:tree does

### ISSUE THREAD

**Issue by smuda** [AyoyAB/Ayoy-Maven-License-Verifier-Plugin#18]
This results in more licenses being detected than is really the case. It seems to show itself especially when using dependencyManagement, such as spring-boot-dependencies.
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <!-- Import dependency management from Spring Boot -->
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${version.org.springframework.boot}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by smuda** [comment]
@madsop @Tibor17 
I've done a major rewrite of the plugin as it was finding much more dependencies than dependency:tree and also much slower.

Just to make sure I haven't messed anything up, would you be able to checkout the branch "issue18" and give it a run?

One thing that is new is that is now verifies the license for the component of the pom, so make sure you have a license entered into the pom.

**Comment by smuda** [comment]
I've now merged this to develop and released a new version.

**Comment by madsop** [comment]
Hi, @smuda! Sorry about the very late response from my side, haven't been able to prioritize this for a while.

Good news, however. I just tried out 1.1.0 on our project, and it works like a charm! Thanks!

**Comment by Tibor17** [comment]
@smuda 
I am back and I have a question regading the dependencies resolution.
How do we do it right now? Because I remember that we took the direct dependencies written in the POM and we resolved them separately. Then there was an issue that an exclusion written below one of these dependencies was ignored basically and we checked the license of the excluded artifact and also its transitive deps.

The ideal solution is to let it be on Maven Resolver which return a bunch of dependencies and these should be checked. I know that you wanted to have a pretty log printing the depth of inheritance and now I am not sure if this can be guaranteed with the resolver, maybe.
